name: Study AI+ Auto Host

on:
  # Allow manual triggering
  workflow_dispatch:

  # Auto-run every 2 days at 3AM EAT (UTC+3)
  schedule:
    - cron: '0 0 */2 * *'  # 0:00 UTC every 2 days = 3:00 AM Ethiopia

jobs:
  run-app:
    runs-on: windows-latest  # Or self-hosted if you want
    timeout-minutes: 2880    # 48 hours = 2 days

    steps:
      - name: 🧼 Clean Up Previous Runs (Optional)
        run: echo "Stopping any prior services..."

      - name: 🧠 Confirm Current Time is 3AM EAT
        run: |
          $currentTime = (Get-Date).ToUniversalTime().AddHours(3)
          Write-Output "EAT Time: $($currentTime.ToString('HH:mm'))"
          if ($currentTime.Hour -ne 3) {
            Write-Output "❌ Not 3 AM EAT. Exiting..."
            exit 1
          } else {
            Write-Output "✅ It's 3 AM. Proceeding..."
          }

      - name: ⚙️ Start Study AI+ Firebase Server
        run: |
          echo "Starting server..."
          # Insert actual Firebase serve/start command
          # Example:
          # firebase emulators:start --only hosting

      - name: ⏱️ Keep Alive
        run: |
          echo "Keeping service alive for 48 hours"
          Start-Sleep -Seconds 172800  # 48 hours = 172800 seconds
